# .github/workflows/inspect-image.yml

name: Inspect Container Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "inspect"
  inspect:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to the GitHub Container Registry using the org-level secret
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # The username can still be the github.actor
          username: ${{ github.actor }}
          # Use the organization-level secret for the password
          password: ${{ secrets.DEPLOYMENT_PAT }}

      # Step to pull the container image
      - name: Pull container image
        run: docker pull ghcr.io/nirmata/cluster:4.22.11

      # Step to run docker inspect on the image
      - name: Inspect image
        run: docker inspect ghcr.io/nirmata/cluster:4.22.11
