name: Get Repo Versions

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Select a release branch'
        required: true
        default: 'release/4.22'
        type: choice
        options:
          - release/4.22
          - release/4.23
          - release/4.24
      release_tag:
        description: 'Enter a tag for the release'
        required: true
        type: string
env:
  username: ${{secrets.DEPLOYMENT_USERNAME}}
  password: ${{secrets.DEPLOYMENT_PAT}}

jobs:
  get-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [ "nirmata/java-security", "nirmata/java-config"]  # Add your repositories here
    steps:
      - name: Checkout release management repo
        uses: actions/checkout@v4

      # Step 2: Set up Git configuration (for tagging)
      - name: Set up Git
        run: |
          git config --global user.name ${{secrets.DEPLOYMENT_USERNAME}}
          git config --global user.email "github-actions@github.com"

      # Step 3: Loop through each Java repository and perform actions
      - name: Handle java-activity repository
        run: |
          git clone https://github.com/nirmata/java-activity.git
          cd java-activity
          git fetch --tags
          # Remove the existing tag if it exists
          git tag -d ${{ github.event.inputs.release_tag }} || true
          git push --delete origin ${{ github.event.inputs.release_tag }} || true
          # Checkout the selected branch
          git checkout ${{ github.event.inputs.release_branch }}
          # Tag the branch with the given tag
          git tag ${{ github.event.inputs.release_tag }}
          git push origin ${{ github.event.inputs.release_tag }}
          # Trigger the master.yml action for java-activity
          # curl -X POST \
          #   -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          #   -d '{"ref":"${{ github.event.inputs.release_branch }}"}' \
          #   https://api.github.com/repos/nirmata/java-activity/actions/workflows/master.yml/dispatches

